In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import plotly.graph_objects as go
import plotly.express as px
import plotly.offline as py
py.init_notebook_mode(connected=True)
import warnings
warnings.filterwarnings("ignore")
from scipy.stats import ttest_ind, ttest_1samp
import gc

SMOOTHING = 3

In [2]:
def clean_data(df):
    if "Unnamed: 0" in df.columns:
        df.drop("Unnamed: 0", axis=1, inplace=True)
        
    for col in df.columns:
        df[col] = df[col].astype(str).str.rstrip('%').str.replace(',', '')
        try:
            df[col] = df[col].astype(float)
        except:
            pass
        
    df.set_index(df.columns[0], inplace=True)
    
    return df

In [3]:
example_agents_df = clean_data(pd.read_csv(f"https://raw.githubusercontent.com/IronicNinja/valorant-stats/master/agents_data/all/agents_competitive_tier%3D3.csv"))
example_agents_df

,KD,Kills,Deaths,Assists,Win Rate,Pick Rate,ACS,First Blood,Num Matches
Agent Name,,,,,,,,,
Sage,0.78,11.5,14.7,4.2,51.9,18.8,164.0,11.7,9231.0
Raze,0.90,13.1,14.6,4.3,44.2,11.7,207.0,13.9,5763.0
Jett,1.01,14.3,14.1,4.1,53.8,10.8,210.0,15.2,5304.0
Reyna,1.01,14.7,14.6,3.9,48.5,10.3,224.0,14.7,5049.0
Viper,0.80,11.0,13.9,4.3,49.3,6.9,165.0,11.8,3417.0
Killjoy,0.86,12.6,14.7,4.3,51.6,6.6,185.0,12.2,3264.0
Phoenix,0.99,13.1,13.3,4.2,62.3,6.3,202.0,14.7,3111.0
Omen,0.85,12.6,14.7,4.5,53.4,6.0,189.0,14.0,2958.0
Sova,0.80,12.1,15.1,5.4,49.0,5.1,182.0,13.4,2499.0
Brimstone,0.89,12.8,14.3,5.6,54.3,4.8,192.0,11.1,2346.0
Skye,0.76,10.4,13.7,3.6,52.6,3.9,149.0,10.9,1938.0
Yoru,0.86,12.2,14.2,3.3,52.6,3.9,186.0,14.9,1938.0
Cypher,0.95,14.5,15.3,5.0,36.4,2.3,193.0,8.8,1122.0
Breach,0.75,11.4,15.2,4.4,52.4,2.2,161.0,11.3,1071.0
Astra,1.20,15.3,12.8,4.8,50.0,0.4,217.0,8.2,204.0

In [ ]:
def avg_visualization(df, name, name2 = "Agents"):
    tmp_df = pd.DataFrame(df.mean(), columns=[name]).sort_values(name, ascending=False).round(3)
    fig = px.bar(tmp_df, y=name, color=name, color_continuous_scale="Viridis")
    fig.update_layout(
        title={'text': f"Average {name} of {name2}", 'x': 0.5,
                             'xanchor': 'center', 'font': {'size': 16}},
        xaxis_title="", yaxis_title=f"{name}", showlegend=False
    )
    fig.show()